### ISSUE TITLE
Stale pyTiVo version

### ISSUE THREAD

**Issue by JonMikelV** [noinip/docker-pytivo#3]
Is there a reason the 07 Aug. 2017 commit was commented with "new version of pytivo" but still contained the 2014-12-24 lucasnz version at http://repo.or.cz/w/pyTivo/wmcbrine/lucasnz.git/snapshot/bbddd6221fecbfc9172f8c78f64bfe69d02cee8a.tar.gz instead of the more current 2016-04-06 version at http://repo.or.cz/pyTivo/wmcbrine/lucasnz.git/snapshot/fed77397491e1dc1ffb0fc400998542a5eec8866.tar.gz?

If it was just a typo (same URL was removed then added back) is it enough just to do a Pull request with the new URL or is other handling needed to get the newer version into the container?

**Comment by JonMikelV** [comment]
@noinip, sorry to bug you more directly, but I'm curious if you are still maintaining this?

**Comment by noinip** [comment]
@JonMikelV Sorry... not really. I update it sometimes. There's a pull request out there now so I'll probably work on it a little now. I kind of quit using my tivo so....

As far as the version..  I don't know, probably a mistake. I'll be updating that at least to whatever is newest.
